### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by roelvangils** [a11yproject/a11yproject.com#508]
I'm hoping and willing to contribute to this great project soon, but I'm running into to some trouble getting the project to run locally.

I followed the instructions in README.me, updated my Ruby installation and installed all the necessary gems. However, when trying to run `jekyll serve`, I am greeted with this message:

```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/plugin_manager.rb:46:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'
```

I'm experienced using front-end technology, but haven't used Jekyll before. So perhaps someone can point me in the right direction to get the project running.

**Comment by joe-watkins** [comment]
Arghh! Getting Jekyll to work can be a pain in certain environments. Here are a couple things to try:

1. Try `bundle exec jekyll serve` vs. `jekyll serve`
2. Visit Jekyll's troubleshooting page -- there is info there about MacOS near bottom. https://jekyllrb.com/docs/troubleshooting/

**Comment by scottaohara** [comment]
just went through the (re)install process myself, on a new machine.  All I had to do was make sure homebrew was up to date, and then everything worked just fine after that.

**Comment by roelvangils** [comment]
Thanks, @scottaohara. I believe you. Unfortunately, I don't have access to a fresh installation of macOS 😉 I'm pretty sure my issues are not related to this Jekyll project. They're probably related to the (newer) Homebrew version of Ruby I had to install. I'll try to uninstall it and re-install Ruby some other way.

**Comment by scottaohara** [comment]
good luck!

**Comment by svinkle** [comment]
@roelvangils Please update this thread if you get it working; it would be great to have some extra documentation available if others run into the same issue.

**Comment by svinkle** [comment]
@roelvangils, did this get resolved?

**Comment by scottaohara** [comment]
@roelvangils one more ping to see if this worked out ok?

**Comment by ericwbailey** [comment]
Closing due to inactivity.
